name: eval_env

on:
  push:
    branches:
      - master  # Replace 'main' with your branch name if different
  pull_request:
    branches:
      - master  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # Adjust Python version as per your requirements

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Create Conda environment
        run: conda env create -f home/runner/work/DTLN/DTLN/eval_env.yml

      - name: Activate Conda environment and install dependencies
        run: |
          conda run -n eval_env pip install -r requirements.txt

      - name: Run tests
        run: |
          conda run -n eval_env pytest dtln/_main_.py
