name: eval_env

on:
  push:
    branches:
      - master  # Replace 'main' with your branch name if different
  pull_request:
    branches:
      - master  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # Adjust Python version as per your requirements

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Conda
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends python3-pip python3-dev
          python -m pip install --upgrade pip setuptools wheel

      - name: Set up Conda environment
        run: |
          conda env create -f dtln\eval_env.yml
          conda activate eval_env

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust as per your project setup

      - name: Run tests
        run: |
          pytest dtln\_main_.py
